# Generated by Django 3.2.8 on 2021-10-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Julius', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
